name: workflow
on: push
jobs:
  clone-down-job: 
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Clone-down
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  build-job:
    needs: clone-down-job
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/build-app.sh
      - run: ci/build-app.sh
      
      

  test-job: 
    needs: clone-down-job
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/unit-test-app.sh
      - run: ci/unit-test-app.sh
      
  
