name: workflow
on: push
jobs:
  clone-down-job: 
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Clone-down
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  build-job:
    needs: clone-down-job
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/build-app.sh
      - run: ci/build-app.sh
      
      

  test-job: 
    needs: clone-down-job
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/unit-test-app.sh
      - run: ci/unit-test-app.sh
    
  docker-image-job:
    needs: test-job && build-job
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Login to docker
        uses: docker/login-action@v1
        with: 
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: my-org/my-image:latest

