name: workflow
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Build
        uses: actions/checkout@v2
      - run: chmod +x ci/build-app.sh
      - run: ci/build-app.sh
  test-job: 
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Test
        run: chmod +x ci/unit-test-app.sh
      - run: ci/unit-test-app.sh
  clone-down-job: 
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
